version: '3.6'

services:

  nginx:
    restart: always
    container_name: nginx
    hostname: nginx
    networks:
      static-network:
        ipv4_address: $NGINX_STATIC_IP_ADDRESS
    image: nginx:${NGINX_VERSION}
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_DIR}/nextcloud/site:/var/www/html
    environment:
      TZ: ${TIMEZONE}
    links:
      - nextcloud

  mysql8:
    container_name: mysql8
    hostname: mysql8
    networks:
      static-network:
        ipv4_address: $MYSQL8_STATIC_IP_ADDRESS
    restart: always
    image: mysql:${MYSQL_VERSION}
    ports:
      - "3306:3306"
    volumes:
      - ${PROJECT_DIR}/nextcloud/db:/var/lib/mysql8
      - ./mysql8/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD=: ${MYSQL_PASSWORD}
      TZ: ${TIMEZONE}

  nextcloud:
    hostname: nextcloud
    privileged: true
    restart: always
    container_name: nextcloud
    networks:
      static-network:
        ipv4_address: $NEXTCLOUD_STATIC_IP_ADDRESS
    build:
      context: ./images/nextcloud
      args:
        - uid=${USER_ID}
        - gid=${GROUP_ID}
        - version=${NEXT_CLOUD_VERSION}
    links:
      - mysql8
    volumes:
      - ${PROJECT_DIR}/nextcloud/site:/var/www/html
      - ./images/nextcloud/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    environment:
      TZ: ${TIMEZONE}

networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet: $NETWORKS_SUBNET

