version: '3.6'

services:

  nginx:
    restart: always
    container_name: nginx
    hostname: nginx
    networks:
      static-network:
        ipv4_address: $NGINX_STATIC_IP_ADDRESS
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_DIR}/nextcloud/site:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${STORAGE_DIR}/logs:/var/log/nginx
      - ${STORAGE_DIR}/sockets:/var/run
    environment:
      TZ: ${TIMEZONE}
    links:
      - nextcloud

  mysql8:
    user: "${USER_ID}:${GROUP_ID}"
    container_name: mysql8
    hostname: mysql8
    networks:
      static-network:
        ipv4_address: $MYSQL8_STATIC_IP_ADDRESS
    restart: always
    build:
      context: ./images/mysql8
      args:
        - uid=${USER_ID}
        - gid=${GROUP_ID}
    ports:
      - "3306:3306"
    volumes:
      - ${STORAGE_DIR}/databases/mysql8:/var/lib/mysql
      - ./mysql8/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD=: ${MYSQL_PASSWORD}
      TZ: ${TIMEZONE}

  nextcloud:
    hostname: nextcloud
    privileged: true
    restart: always
    container_name: nextcloud
    networks:
      static-network:
        ipv4_address: $NEXTCLOUD_STATIC_IP_ADDRESS
    build:
      context: ./images/nextcloud
      args:
        - uid=${USER_ID}
        - gid=${GROUP_ID}
        - version=${NEXT_CLOUD_VERSION}
    links:
      - mysql8
    volumes:
      - ${PROJECT_DIR}/nextcloud/site:/var/www/html
      - ./images/nextcloud/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ${STORAGE_DIR}/sockets:/var/run
    environment:
      TZ: ${TIMEZONE}

  netatalk:
    hostname: netatalk
    privileged: true
    restart: always
    container_name: netatalk
    networks:
      static-network:
        ipv4_address: $NETATALK_STATIC_IP_ADDRESS
    build:
      context: ./images/netatalk
      args:
        - version=${NETATALK_VERSION}
    ports:
      - "548:548"
    volumes:
      - ${HOME_DIR}/share:/media/share
      - ./netatalk/afp.conf:/etc/afp.conf
    environment:
      AFP_USER: ${AFP_USER}
      AFP_PASSWORD: ${AFP_PASSWORD}
      AFP_UID: ${USER_ID}
      AFP_GID: ${GROUP_ID}
      TZ: ${TIMEZONE}

networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet: $NETWORKS_SUBNET

